# Generated by Django 3.1.3 on 2020-11-04 07:12

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('slug', models.CharField(max_length=120, unique=True)),
                ('thumbnail', models.ImageField(upload_to='blog/images/')),
                ('content', ckeditor.fields.RichTextField(blank=True)),
            ],
        ),
    ]
