# Generated by Django 3.1.3 on 2020-11-21 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20201121_1531'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPageSeo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seo_title', models.CharField(blank=True, max_length=120, null=True)),
                ('seo_desc', models.TextField(blank=True, null=True)),
                ('seo_keywords', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
