# Generated by Django 3.1.3 on 2020-11-04 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_about'),
    ]

    operations = [
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill', models.CharField(max_length=120)),
                ('Forwarding', models.CharField(max_length=120)),
                ('pickup', models.DateField()),
                ('destination', models.CharField(max_length=120)),
                ('consignee', models.CharField(max_length=120)),
                ('status', models.CharField(max_length=120)),
            ],
        ),
    ]
