# Generated by Django 3.1.3 on 2020-11-05 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20201105_1124'),
    ]

    operations = [
        migrations.RenameField(
            model_name='track',
            old_name='Forwarding',
            new_name='forwarding',
        ),
        migrations.RemoveField(
            model_name='track',
            name='status_date',
        ),
        migrations.RemoveField(
            model_name='track',
            name='status_time',
        ),
        migrations.AddField(
            model_name='track',
            name='status_datetime',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='track',
            name='pickup',
            field=models.DateTimeField(),
        ),
    ]
