# Generated by Django 3.1.3 on 2020-11-06 05:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20201105_2245'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='track',
            name='rec_by',
        ),
        migrations.RemoveField(
            model_name='track',
            name='status_datetime',
        ),
        migrations.AlterField(
            model_name='track',
            name='bill',
            field=models.CharField(max_length=120, unique=True),
        ),
        migrations.CreateModel(
            name='TrackStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_datetime', models.DateTimeField(null=True)),
                ('rec_by', models.CharField(max_length=120, null=True)),
                ('track_status', models.CharField(max_length=250, null=True)),
                ('status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='status_track', to='main.track')),
            ],
        ),
    ]
