# Generated by Django 3.1.3 on 2020-11-21 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_aboutpageseo_homepageseo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trackstatus',
            old_name='rec_by',
            new_name='locations',
        ),
    ]
